# Generated by Django 5.1.2 on 2024-10-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joystickJunctionApp', '0002_alter_productdetail_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='productCategory',
            field=models.CharField(choices=[('ADVENTURE', 'ADVENTURE'), ('Sports', 'Sports'), ('Shooting', 'Shooting'), ('Consoles', 'Consoles')], max_length=40, verbose_name='Product Category'),
        ),
    ]
