# Generated by Django 5.1.2 on 2024-10-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joystickJunctionApp', '0004_alter_productdetail_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='productCategory',
            field=models.CharField(choices=[('PARTIALLY PHYSICAL', 'PARTIALLY PHYSICAL'), ('SENSORY', 'SENSORY'), ('INTELLECTUAL', 'INTELLECTUAL'), ('MENTAL HEALTH AND EMOTIONAL', 'MENTAL HEALTH AND EMOTIONAL')], max_length=40, verbose_name='Product Category'),
        ),
    ]
